Models/Category.cs
namespace MovieApp.Models
{
    public class Category
    {
        public int Id { get; set; } 
        public string Name { get; set; }

    }
}

Models/Movie.cs
namespace MovieApp.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public int CategoryId { get; set; }
    }
}

Models/MovieCategoryModel.cs
using System.Collections.Generic;

namespace MovieApp.Models
{
    public class MovieCategoryModel
    {
        public Movie Movie {get;set;}
        public IEnumerable<Movie> Movies { get; set; }
        public IEnumerable<Category> Categories { get; set; }


    }
}

Models/Repository.cs
using System.Collections.Generic;
using System.Linq;

namespace MovieApp.Models
{
    public static  class Repository
    {
        private static List<Movie>  _movies = null;

        static Repository (){
            _movies = new List<Movie>()
            {
                new Movie(){
                    Id=1,
                    Name ="Love and Pride",
                    Description ="Romantic",
                    ImageUrl ="1.jpg"
                },

                                new Movie(){
                    Id=2,
                    Name ="Hunger Games",
                    Description ="Fantastic",
                    ImageUrl ="2.jpg"
                },
                                new Movie(){
                    Id=3,
                    Name ="Social Network",
                    Description ="Software",
                    ImageUrl ="3.jpg"
                },
                                new Movie(){
                    Id=4,
                    Name ="Lara Croft Tomb Raider",
                    Description ="Action",
                    ImageUrl ="4.jpg"
                }
            };
        }

        public static List<Movie> Movies {
            get{
                return _movies;
            }
        }

        public static void AddMovie(Movie entity){
            _movies.Add(entity);
        }

        public static Movie GetById(int id){
            return _movies.FirstOrDefault(p => p.Id == id);
        }
    }
}

Controllers/HomeController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MovieApp.Data;
using MovieApp.Models;

namespace MovieApp.Controllers
{
    public class HomeController:Controller
    {
        public IActionResult Index(int? id)
        {
            
            var movies = MovieRepository.Movies;

            if(id!=null){
                movies = movies.Where(i => i.CategoryId == id).ToList();
            }
            // MovieCategoryModel model  = new MovieCategoryModel();
            // model.Categories = CategoryRepository.Categories;
            // model.Movies = MovieRepository.Movies;

            return View(movies);
        }
        
       public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            // MovieCategoryModel model = new MovieCategoryModel();
            // model.Categories = CategoryRepository.Categories;
            // model.Movie = MovieRepository.GetById(id);
            return View(MovieRepository.GetById(id));
        }
    }
}

Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;

namespace MovieApp.Controllers
{
    public class MovieController:Controller
    {
     public IActionResult Index()
     {
         return View();
     }
    public IActionResult CreateAction()
     {
         return View();
     }
     
     
    public IActionResult List()
     {
         return View();
     }

     
    public IActionResult Details()
     {
         return View();
     }
     
     
    }
}

ViewComponents/CategoryMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Data;

namespace MovieApp.ViewComponents
{
    public class CategoryMenuViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke(){

            if(RouteData.Values["action"].ToString() == "Index"){
                 ViewBag.SelectedCategory = RouteData?.Values["id"];
            }
            return View(CategoryRepository.Categories);
        }
    }
}

Views/Home/Contact.cshtml
<h1>Home/Contact</h1>

Views/Home/Details.cshtml
@model Movie
<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("CategoryMenu")
        @* @Html.Partial("_menu",Model.Categories) *@
    </div>
    <div class="col-md-9">
          <div class="card mb-3">
<div class="card-body">
    <div class="row no-gutter">
    <div class="row">
        <div class="col-md-4">
            <img src="~/img/@Model.ImageUrl" alt="@Model.Description" width="200px" height="200px">
        </div>
        <div class="col-md-8" style="padding-left:60px">
            <div class="card-body">
                <h5 class="card-title">
                    @* <a href="/home/details/@item.Id">
                    @item.Name
                    </a> *@
                    <a asp-action="Details" asp-controller="Home"
                    asp-route-id="@Model.Id">
                    @Model.Name
                    </a>
                </h5>

                <p class="card-text">
                    @Model.Description
                </p>
                <p class="card-text">
                    <small class="text-muted">
                        3 days ago
                    </small>
                </p>

            </div>
        </div>

    </div>
    </div>
</div>


</div>  
    </div>
</div>

Views/Home/Index.cshtml
@model IEnumerable<Movie>
<div class="row">
    <div class="col-md-3">
        @* @Html.Partial("_menu",Model.Categories) *@
        @await Component.InvokeAsync("CategoryMenu")
    </div>
    <div class="col-md-9">
        @Html.Partial("_movies",Model)
    </div>
</div>

Views/Home/_movies.cshtml
@model IEnumerable<Movie>

@foreach (var item in Model)
{
  <div class="card mb-3">
    <div class="row">
        <div class="col-md-3">
            <img src="~/img/@item.ImageUrl" alt="@item.Description" width="200px" height="200px">
        </div>
        <div class="col-md-9">
            <div class="card-body">
                <h5 class="card-title">
                    @item.Name
                </h5>

                <p class="card-text">
                    @item.Description
                </p>
                <p class="card-text">
                    <small class="text-muted">
                        3 days ago
                    </small>
                </p>

            </div>
        </div>

    </div>
</div>  
}

Views/Movie/Details.cshtml
<h1>Movie/Details </h1>

Views/Movie/Index.cshtml
<h1>Movie/Index</h1>

Views/Movie/List.cshtml
<h1>Movie/List</h1>

Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>


@foreach (var category in Model)
{
    <div class="list-group">
    <a  asp-controller="Home" asp-action="Index" 
    asp-route-id = "@category.Id" class="list-group-item list-group-item-action @(ViewBag.SelectedCategory==category.Id.ToString()?"active":"")">
        @category.Name  
    </a>
</div>
}    

Views/Shared/_footer.cshtml
<div class="footer py-3 mt-3">
    <div class="container">
        <span class="text-muted">
            Place footer content here
        </span>
    </div>
</div>

Views/Shared/_layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/modules/bootstrap/dist/css/bootstrap.min.css"   >
    <title>Movie App</title>
</head>
<body>
    <header>
        @Html.Partial("_navbar")
    </header>
    <main>
     <div class="container mt-4">
         @RenderBody()
     </div>
    </main>
    <footer>
        @Html.Partial("_footer")
    </footer>
    @RenderBody()
</body>
</html>

Views/Shared/_menu.cshtml
@model IEnumerable<Category>


@foreach (var category in Model)
{
    <div class="list-group">
    <a href="" class="list-group-item list-group-item-action active">
        @category.Name
    </a>
</div>
}    

Views/Shared/_navbar.cshtml
<div class="navbar navbar-expand-sm bg-primary navbar-dark">
    <div class="container">
        <a href="/" class="navbar-brand">Movie App</a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="/login" class="nav-link">Login</a>
            </li>
                <li class="nav-item">
                <a href="/register" class="nav-link">Register</a>
            </li>
        </ul>
    </div>
</div>